from pathlib import Path
from typing import List
import logging
from pipeline.utils.decode_common import decode_file, extract_decode_units_with_time, decode_valid_chunks, get_config_from_file
import pandas as pd

# def _break_bin(bin_paths):
#     """
#     To simulate packet loss, multiple blocks of 144 bytes are intentionally corrupted at arbitrary positions within the 144-byte cycle.
#     """
#     number = 1
#     position = 1
#     packet_block = 144

#     start = packet_block*position
#     end = packet_block*position + packet_block*number 

#     broken_bin = bin_paths[:start] + bin_paths[end:]
#     print(f'is them same {broken_bin == bin_paths}')
#     return broken_bin

def run(folder_name: str) -> List[Path]:
    """
    Entry point of pipeline step 5.
    Collects step4 artifacts inside the given folder.
    """
    logger = logging.getLogger(__name__)

    print(folder_name)
    folder = Path(folder_name)
    logger.debug("folders=%s", folder)
    if not folder.exists():
        raise FileNotFoundError(f"{folder} does not exist")
    bin_paths = _collect_step4_files(folder)

    for bin_path in bin_paths:

        config = get_config_from_file(bin_path)
        decoder = config.decoder
        data = read_decodable_data(bin_path)
        decoded_data = decoder(data)
        new_path = bin_path.parent / f"decoded_{bin_path.name}"
        # print(decoded_data)
        df = pd.DataFrame(decoded_data)
        df.to_csv(new_path)
    return 
def read_decodable_data(bin_path):

    df = pd.read_csv(bin_path)
    data_str = df["Data"].str.cat()
    # print(data_str)

    data = data = bytes.fromhex(data_str)
    # print(data)

    return data



def _collect_step4_files(folder: Path) -> List[Path]:
    """
    Collect files generated by step4.
    """
    
    return sorted(folder.glob("step4*.csv"))


