from pathlib import Path
from typing import List
import logging


def run(folder_name: str) -> List[Path]:
    """
    Entry point of pipeline step 5.
    Collects step4 artifacts inside the given folder.
    """
    logger = logging.getLogger(__name__)

    folder = Path(folder_name)
    logger.debug("folders=%s", folder)
    if not folder.exists():
        raise FileNotFoundError(f"{folder} does not exist")

    return _collect_step4_files(folder)


def _collect_step4_files(folder: Path) -> List[Path]:
    """
    Collect files generated by step4.
    """
    return sorted(folder.glob("step4_*"))