from pathlib import Path
from typing import List
import logging
from decoder import main_log_decoder, adcs_main_decoder
import pandas as pd


# def _break_bin(bin_files):
#     """
#     To simulate packet loss, multiple blocks of 144 bytes are intentionally corrupted at arbitrary positions within the 144-byte cycle.
#     """
#     number = 1
#     position = 1
#     packet_block = 144

#     start = packet_block*position
#     end = packet_block*position + packet_block*number 

#     broken_bin = bin_files[:start] + bin_files[end:]
#     print(f'is them same {broken_bin == bin_files}')
#     return broken_bin

def run(folder_name: str) -> List[Path]:
    """
    Entry point of pipeline step 5.
    Collects step4 artifacts inside the given folder.
    """
    logger = logging.getLogger(__name__)

    folder = Path(folder_name)
    logger.debug("folders=%s", folder)
    if not folder.exists():
        raise FileNotFoundError(f"{folder} does not exist")
    bin_files = _collect_step4_files(folder)

    # bin_files = _break_bin(bin_files)

    for bin_file in bin_files:
        _check_TLM_type(folder,bin_file)

    return bin_files


def _collect_step4_files(folder: Path) -> List[Path]:
    """
    Collect files generated by step4.
    """
    return sorted(folder.glob("step4_*"))

def _check_TLM_type(folder, bin_file):
    filetype = bin_file.stem.split('_')[-1][:3]
    
    match filetype:
        case "001":
            print('main_exe_log')
            _decode_main_exe(folder, bin_file)
        case "010":
            print('auto_packet')
        case "011":
            print("ADCS high")
            _decode_adcs_high(folder, bin_file)

def replace_folder_name(folder):
    parts = list(folder.parts)
    parts[1] = "final_product"   # 2段目を書き換え
    new_folder_name = Path(*parts)
    return new_folder_name

def save_csv_file(csv_path, data):
    df = pd.DataFrame(data)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(csv_path,index=False)
    print(f'saved {csv_path}')


def _decode_main_exe(folder,bin_file):
    lines = main_log_decoder.decode(bin_file)
    new_folder_name = replace_folder_name(folder)
    csv_path = new_folder_name  / "obc_decoded.csv"
    save_csv_file(csv_path, lines)
    return csv_path


def _decode_adcs_high(folder,bin_file):
    decoded_list = adcs_main_decoder.decode(bin_file)
    new_folder_name = replace_folder_name(folder)
    csv_path = new_folder_name  / "adcs_HK_decoded.csv"
    save_csv_file(csv_path, decoded_list)

    return csv_path