from pathlib import Path
from typing import List
import logging
from decoder import vertecs_process_log, adcs_main_decoder
import pandas as pd

def run(folder_name: str) -> List[Path]:
    """
    Entry point of pipeline step 5.
    Collects step4 artifacts inside the given folder.
    """
    logger = logging.getLogger(__name__)

    folder = Path(folder_name)
    logger.debug("folders=%s", folder)
    if not folder.exists():
        raise FileNotFoundError(f"{folder} does not exist")
    bin_files = _collect_step4_files(folder)

    for bin_file in bin_files:
        _check_TLM_type(folder,bin_file)

    return bin_files


def _collect_step4_files(folder: Path) -> List[Path]:
    """
    Collect files generated by step4.
    """
    return sorted(folder.glob("step4_*"))

def _check_TLM_type(folder, bin_file):
    filetype = bin_file.stem.split('_')[-1][:3]
    
    match filetype:
        case "001":
            print('main_exe_log')
            _decode_main_exe(folder, bin_file)
        case "010":
            print('auto_packet')
        case "011":
            print("ADCS high")
            _decode_adcs_high(folder, bin_file)


def _decode_main_exe(folder,bin_file):
    lines = vertecs_process_log.decode(bin_file)


    parts = list(folder.parts)
    parts[1] = "final_product"   # 2段目を書き換え
    new_path = Path(*parts)
    # print(new_path)
    # exit()
    csv_path = new_path  / "obc_decoded.csv"
    print(csv_path)
    csv_path.parent.mkdir(parents=True, exist_ok=True)

    with open(csv_path, "w", encoding="utf-8") as f:
        f.writelines(lines)

    return csv_path


def _decode_adcs_high(folder,bin_file):
    decoded_list = adcs_main_decoder.decode(bin_file)
    df = pd.DataFrame(decoded_list)


    parts = list(folder.parts)
    parts[1] = "final_product"   # 2段目を書き換え
    new_path = Path(*parts)
    # print(new_path)
    # exit()
    csv_path = new_path  / "adcs_HK_decoded.csv"
    print(csv_path)
    csv_path.parent.mkdir(parents=True, exist_ok=True)

    # os.makedirs(f'final_products/{timestamp}',exist_ok=True)
    output_file = csv_path
    df.to_csv(output_file,index=False)
    # with open(csv_path, "w", encoding="utf-8") as f:
    #     f.writelines(lines)

    return csv_path