from pathlib import Path
from typing import List
import logging
from pandas.errors import EmptyDataError
from pipeline.utils.decode_common import get_config_from_file
import pandas as pd


def run(folder_name: str | Path, out_dir: str | Path) -> List[Path]:
    """
    Entry point of decode_payloads.
    Collects step4 artifacts inside the given folder.
    """
    logger = logging.getLogger(__name__)

    folder = Path(folder_name)
    logger.debug("folders=%s", folder)
    if not folder.exists():
        raise FileNotFoundError(f"{folder} does not exist")
    bin_paths = _collect_step4_files(folder)
    output_dir = Path(out_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    written_paths = []
    for bin_path in bin_paths:

        config = get_config_from_file(bin_path)
        if config is None:
            logger.warning("Skipping unsupported decode payload file: %s", bin_path)
            continue
        decoder = config.decoder
        move_lost_units_report(bin_path, output_dir)
        data = read_decodable_data(bin_path)
        if not data:
            logger.info("Skipping empty decode payload file: %s", bin_path)
            continue
        decoded_data = decoder(data)
        new_path = output_dir / f"decoded_{bin_path.name}"
        df = pd.DataFrame(decoded_data)
        df.to_csv(new_path)
        written_paths.append(new_path)

    return written_paths


def move_lost_units_report(bin_path: Path, output_dir: Path) -> Path | None:
    source = bin_path.with_name(f"{bin_path.stem}_missing.csv")
    if not source.exists():
        return None

    destination = output_dir / f"decoded_{source.name}"
    return source.replace(destination)


def read_decodable_data(bin_path):

    try:
        df = pd.read_csv(bin_path)
    except EmptyDataError:
        return b""

    if "Data" not in df or df.empty:
        return b""

    data_str = df["Data"].str.cat()

    data = bytes.fromhex(data_str)

    return data



def _collect_step4_files(folder: Path) -> List[Path]:
    """
    Collect files generated by step4.
    """
    return sorted(
        path
        for path in folder.glob("step4_concat_data_ID_*.csv")
        if not path.name.endswith("_missing.csv")
    )
